version: '3.7'

services:
  backend:
    image: ysndlklc/backend-demo
    restart: always

    ports:
      - 5020:5020
    networks:
      - net-for-demo

  frontend:
    image: ysndlklc/frontend-demo
    restart: always

    ports:
      - 3000:3000
    networks:
      - net-for-demo

networks:
  net-for-demo:
    driver: bridge