name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push-be:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: |
        docker build ./be --file Dockerfile --tag ysndlklc/backend-demo
        docker push ysndlklc/backend-demo

  build-push-fe:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: |
        docker build ./fe --file Dockerfile --tag ysndlklc/frontend-demo
        docker push ysndlklc/frontend-demo
      
